language: python
python:
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script: python -m unittest
notifications:
  email:
    recipients:
      - contact@tchekda.fr
    on_success: never # default: change
    on_failure: always # default: always